[package]
name = "howmanysmall/error"                                                                # TODO: Change to Bura Games org
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dependencies]
